// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: control_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time int32 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Rank int32 `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
}

func (x *Req) Reset() {
	*x = Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req) ProtoMessage() {}

func (x *Req) ProtoReflect() protoreflect.Message {
	mi := &file_control_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req.ProtoReflect.Descriptor instead.
func (*Req) Descriptor() ([]byte, []int) {
	return file_control_service_proto_rawDescGZIP(), []int{0}
}

func (x *Req) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Req) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type Rep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Syn bool `protobuf:"varint,1,opt,name=syn,proto3" json:"syn,omitempty"`
}

func (x *Rep) Reset() {
	*x = Rep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rep) ProtoMessage() {}

func (x *Rep) ProtoReflect() protoreflect.Message {
	mi := &file_control_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rep.ProtoReflect.Descriptor instead.
func (*Rep) Descriptor() ([]byte, []int) {
	return file_control_service_proto_rawDescGZIP(), []int{1}
}

func (x *Rep) GetSyn() bool {
	if x != nil {
		return x.Syn
	}
	return false
}

var File_control_service_proto protoreflect.FileDescriptor

var file_control_service_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x2d, 0x0a, 0x03, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x22, 0x17, 0x0a, 0x03, 0x52, 0x65,
	0x70, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x79, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03,
	0x73, 0x79, 0x6e, 0x32, 0x32, 0x0a, 0x08, 0x53, 0x79, 0x6e, 0x61, 0x43, 0x74, 0x72, 0x6c, 0x12,
	0x26, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x41, 0x6e, 0x64, 0x47, 0x65, 0x74,
	0x4d, 0x73, 0x67, 0x12, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x07, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x70, 0x22, 0x00, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_control_service_proto_rawDescOnce sync.Once
	file_control_service_proto_rawDescData = file_control_service_proto_rawDesc
)

func file_control_service_proto_rawDescGZIP() []byte {
	file_control_service_proto_rawDescOnce.Do(func() {
		file_control_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_control_service_proto_rawDescData)
	})
	return file_control_service_proto_rawDescData
}

var file_control_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_control_service_proto_goTypes = []interface{}{
	(*Req)(nil), // 0: pb.Req
	(*Rep)(nil), // 1: pb.Rep
}
var file_control_service_proto_depIdxs = []int32{
	0, // 0: pb.SynaCtrl.SetTimeAndGetMsg:input_type -> pb.Req
	1, // 1: pb.SynaCtrl.SetTimeAndGetMsg:output_type -> pb.Rep
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_control_service_proto_init() }
func file_control_service_proto_init() {
	if File_control_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_control_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_control_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_service_proto_goTypes,
		DependencyIndexes: file_control_service_proto_depIdxs,
		MessageInfos:      file_control_service_proto_msgTypes,
	}.Build()
	File_control_service_proto = out.File
	file_control_service_proto_rawDesc = nil
	file_control_service_proto_goTypes = nil
	file_control_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SynaCtrlClient is the client API for SynaCtrl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SynaCtrlClient interface {
	SetTimeAndGetMsg(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Rep, error)
}

type synaCtrlClient struct {
	cc grpc.ClientConnInterface
}

func NewSynaCtrlClient(cc grpc.ClientConnInterface) SynaCtrlClient {
	return &synaCtrlClient{cc}
}

func (c *synaCtrlClient) SetTimeAndGetMsg(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Rep, error) {
	out := new(Rep)
	err := c.cc.Invoke(ctx, "/pb.SynaCtrl/SetTimeAndGetMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SynaCtrlServer is the server API for SynaCtrl service.
type SynaCtrlServer interface {
	SetTimeAndGetMsg(context.Context, *Req) (*Rep, error)
}

// UnimplementedSynaCtrlServer can be embedded to have forward compatible implementations.
type UnimplementedSynaCtrlServer struct {
}

func (*UnimplementedSynaCtrlServer) SetTimeAndGetMsg(context.Context, *Req) (*Rep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTimeAndGetMsg not implemented")
}

func RegisterSynaCtrlServer(s *grpc.Server, srv SynaCtrlServer) {
	s.RegisterService(&_SynaCtrl_serviceDesc, srv)
}

func _SynaCtrl_SetTimeAndGetMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SynaCtrlServer).SetTimeAndGetMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SynaCtrl/SetTimeAndGetMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SynaCtrlServer).SetTimeAndGetMsg(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

var _SynaCtrl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SynaCtrl",
	HandlerType: (*SynaCtrlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetTimeAndGetMsg",
			Handler:    _SynaCtrl_SetTimeAndGetMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "control_service.proto",
}
