// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: protoc/sycnMsg.proto

package protoc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rank  uint32 `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	Epoch uint32 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
}

func (x *Res) Reset() {
	*x = Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_sycnMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Res) ProtoMessage() {}

func (x *Res) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_sycnMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Res.ProtoReflect.Descriptor instead.
func (*Res) Descriptor() ([]byte, []int) {
	return file_protoc_sycnMsg_proto_rawDescGZIP(), []int{0}
}

func (x *Res) GetRank() uint32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *Res) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type Resp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sync bool `protobuf:"varint,1,opt,name=sync,proto3" json:"sync,omitempty"`
}

func (x *Resp) Reset() {
	*x = Resp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_sycnMsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resp) ProtoMessage() {}

func (x *Resp) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_sycnMsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resp.ProtoReflect.Descriptor instead.
func (*Resp) Descriptor() ([]byte, []int) {
	return file_protoc_sycnMsg_proto_rawDescGZIP(), []int{1}
}

func (x *Resp) GetSync() bool {
	if x != nil {
		return x.Sync
	}
	return false
}

var File_protoc_sycnMsg_proto protoreflect.FileDescriptor

var file_protoc_sycnMsg_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x73, 0x79, 0x63, 0x6e, 0x4d, 0x73, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x22, 0x2f,
	0x0a, 0x03, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f,
	0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x22,
	0x1a, 0x0a, 0x04, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x79, 0x6e, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x73, 0x79, 0x6e, 0x63, 0x32, 0x34, 0x0a, 0x0a, 0x53,
	0x79, 0x6e, 0x63, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x07, 0x53, 0x79, 0x6e,
	0x63, 0x43, 0x74, 0x6c, 0x12, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x52, 0x65,
	0x73, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x42, 0x09, 0x5a, 0x07, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protoc_sycnMsg_proto_rawDescOnce sync.Once
	file_protoc_sycnMsg_proto_rawDescData = file_protoc_sycnMsg_proto_rawDesc
)

func file_protoc_sycnMsg_proto_rawDescGZIP() []byte {
	file_protoc_sycnMsg_proto_rawDescOnce.Do(func() {
		file_protoc_sycnMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_protoc_sycnMsg_proto_rawDescData)
	})
	return file_protoc_sycnMsg_proto_rawDescData
}

var file_protoc_sycnMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protoc_sycnMsg_proto_goTypes = []interface{}{
	(*Res)(nil),  // 0: protoc.Res
	(*Resp)(nil), // 1: protoc.Resp
}
var file_protoc_sycnMsg_proto_depIdxs = []int32{
	0, // 0: protoc.SyncServer.SyncCtl:input_type -> protoc.Res
	1, // 1: protoc.SyncServer.SyncCtl:output_type -> protoc.Resp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protoc_sycnMsg_proto_init() }
func file_protoc_sycnMsg_proto_init() {
	if File_protoc_sycnMsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protoc_sycnMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_sycnMsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protoc_sycnMsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protoc_sycnMsg_proto_goTypes,
		DependencyIndexes: file_protoc_sycnMsg_proto_depIdxs,
		MessageInfos:      file_protoc_sycnMsg_proto_msgTypes,
	}.Build()
	File_protoc_sycnMsg_proto = out.File
	file_protoc_sycnMsg_proto_rawDesc = nil
	file_protoc_sycnMsg_proto_goTypes = nil
	file_protoc_sycnMsg_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SyncServerClient is the client API for SyncServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SyncServerClient interface {
	SyncCtl(ctx context.Context, in *Res, opts ...grpc.CallOption) (*Resp, error)
}

type syncServerClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncServerClient(cc grpc.ClientConnInterface) SyncServerClient {
	return &syncServerClient{cc}
}

func (c *syncServerClient) SyncCtl(ctx context.Context, in *Res, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/protoc.SyncServer/SyncCtl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncServerServer is the server API for SyncServer service.
type SyncServerServer interface {
	SyncCtl(context.Context, *Res) (*Resp, error)
}

// UnimplementedSyncServerServer can be embedded to have forward compatible implementations.
type UnimplementedSyncServerServer struct {
}

func (*UnimplementedSyncServerServer) SyncCtl(context.Context, *Res) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncCtl not implemented")
}

func RegisterSyncServerServer(s *grpc.Server, srv SyncServerServer) {
	s.RegisterService(&_SyncServer_serviceDesc, srv)
}

func _SyncServer_SyncCtl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Res)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServerServer).SyncCtl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoc.SyncServer/SyncCtl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServerServer).SyncCtl(ctx, req.(*Res))
	}
	return interceptor(ctx, in, info, handler)
}

var _SyncServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protoc.SyncServer",
	HandlerType: (*SyncServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncCtl",
			Handler:    _SyncServer_SyncCtl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protoc/sycnMsg.proto",
}
